### ISSUE TITLE
tracker: grid submersion algorithm

### ISSUE THREAD

**Issue by imrn99** [LIHPC-Computational-Geometry/honeycomb#110]
The first algorithm considered for implementation is a 2D, [Morph](https://internationalmeshingroundtable.com/assets/research-notes/imr32/2011.pdf)-inspired, mesh construction algorithm. This issue is used to group and document the implementation process as well as specific considerations / choices.

## Scope

Some considerations:
- evaluating how combinatorial maps perform in the context of this approach
- evaluating the learning curve of combinatorial maps usage
- ensuring basic correctness & viability before moving on to 3D or parallelization

Some non-considerations (ATM, possibly ever):
- correct capture of highly contrasted (size-wise) geometry features requiring some form of adaptative mesh refinement
- significant work on algorithm writing; our focus is on data structures

### Hypotheses

-  All components of the geometry are located in positive X/Y
- Edges are consistently oriented (i.e. normals of edges making up a face all point outward / inward, no mix)

### Map generation

**Input**:
- Geometry of interest
- Grid characteristics (length of cell along X/Y-axis)
 
**Algorithm**:

Let `S` be the set of all segments making up the boundaries of the geometry.
Let `PoI` be the set of points of interests of the boundaries (i.e. vertices that must be inserted into the final mesh)
Let `DoI` be the corresponding set of darts of interests
 
For all segments `[A, B]` of `S`: 
- compute the Manhattan distance `d` between cell(A) and cell(B):
    - if  `d == 0`: `A` and `B` belong to the same grid cell
        - Do nothing
    - if `d == 1`: `A` and `B` belong to neighbor cells
        - Compute the intersection `C` between the segment and the grid's edge
        - Split the grid's edge to add `C` on it, add relevant darts to `DoI`
        - Replace segment `[A, B]` by segments `[A, C]`, `[C, B]`
        - Add `C` to `PoI`
    - if `d > 1`: `A` and `B` belong to different, non-neighbor cells
        - Compute all intersections `Ci` between the segment and grid's edges
        - Split grid's edges to add `Ci`s on them, add relevant darts to `DoI`
        - Replace segment `[A, B]` by segments `[A, C1]`, `[C1, C2]`, ..., `[CX, B]`
        - Add all `Ci`s to `PoI`
- if `B` belongs to `PoI`:
    - Insert `B` into the map
    - Add relevant darts to `DoI`

For all points `P` of `PoI`:
- search `S` to find `P'`, the first "next" point to belong to `PoI`
- use `DoI` to build the `[P, P']` segment into the map (this may need some refinement to avoid execution-path inconsistencies)

### Post-processing clip

TBD

## Implementation breakdown

- Handle input geometry
    - [x] read geometry from a serialized file
    - [x] pre-process data to (a) keep what's useful and (b) organize it according to its usage is the main routine
- Generate the overlapping grid
    - [x] compute the boundary box of the input geometry
    - [x] determine grid dimensions (overall span & cells) or read it from user input?
    - [x] generate the grid
- Go through the algorithm described above:
    - [x] TBD
- Finalize results & return:
    - [ ] (optionally) remove the inner or outer cells of the generated map representation
    - [x] ~(optionally) assign attributes value~ not now
    - [x] return the map as an object or serialize it  

## Additional tasks

- [x] document the new member in the user guide
- [ ] add unit tests for components of the algorithm
- [x] visuals would be nice to have with the pseudo-code
