### ISSUE TITLE
rel: road to `1.0.0`

### ISSUE THREAD

**Issue by imrn99** [LIHPC-Computational-Geometry/honeycomb#150]
# `1.0.0`

The crate is reaching a state (feature-wise) which I consider acceptable for a big release. This issue can be used to (a) argue about that claim, and (b) list in detail desirable stuff to do / process before such a release.

## To-Do

- [ ] Go over the public API 
- [ ] Go over internal implemention (the goal is simplification)
- [ ] Go over the documentation
- [ ] Revise public exports & multi-crate gestion (look into `prelude`, `default-features`, & external crate re-exports)
- [ ] Cleanup the GRISUBAL implementation and add extensive, automated test cases
- [ ] Merge the re-written render tool
- [ ] Triple check the dependency tree

details/explanation TBD
