### ISSUE TITLE
enh: crate parallelization

### ISSUE THREAD

**Issue by imrn99** [LIHPC-Computational-Geometry/honeycomb#197]
this issue is used to track and outline tasks related to the parallelization of this crate's code. this includes both kernels/algorithms parallelization as well as modifications to the data structure to make it parallel friendly (== ownership compliant).

## Goals

Primary:
- [ ] Explore possibilities for `grisubal` parallelization
- [ ] Implement a parallel-friendly version of `CMap2`
- [ ] Make it good :)

Secondary:
- [ ] Introduce some parallelization in the building routines
- [ ] Test performance of a parallel cell triangulation routine (of existing cells, not triagnulation of a domain)

**Comment by imrn99** [comment]
# `ParallelCMap2` concept

name tbd, `PMap2` ??

## Main issues / challenges

- Attribute system relies on a bunch of traits so that the manager does not "see" attributes. All traits using `&mut self` would have to be duplicated to have non-mutable method signatures.
- Which sync mechanism to use over what data?
- How to handle darts addition / deletion (i.e. allocation to some extent)?

## Task outline

TBD

**Comment by imrn99** [comment]
# `grisubal` parallelization

## Step 1 / Compute intersection data

this section needs significant changes for it to run in parallel. incidentally, this is the section that scales the worse.

## Step 2 / Insert intersections

the main upgrade here would be precomputing and allocating darts beforehand so that all `splitn_edge` can be replaced with no-alloc variants (thus improving performance AND removing all contention).

the end result should probably be an additional step (~1.9) since having the dart information beforehand allows us to run step 3 in parallel of with step 2.

## Step 3 / Compute edge data

last § + the code for this section can actually be parallelized as-is.

## Step 4 / Insert edges

like in step 2, we can preallocate darts for the new edges & run iterations of this step fully in parallel.

## Observations

not all sections scale the same: for the fixed input `examples/shape.vtk`, using `0.01` grid size instead of `1.0` multiplies the time of each section by:

| section | \_ times longer |
|---|---|
| step1 | 2000 |
| step2 | 100 |
| step 3 | 25 |
| step 4| 40 |

all of these being superseeded by the time taken by grid building (x6000, & the most significant by flat value).

**Comment by imrn99** [comment]
lots of challenges to get the implementation working just right. here's a road ahead:
- #216 
- [ ] finish #220 
    - [ ] add in grisubal changes
    - [ ] benchmark
    - [ ] move collections to components module 
    - [ ] document strong typing implementation & policy
- [ ] expose "retry" APIs
    - [ ] retry a transactional method
    - [ ] retry if there was an issue with attributes merging/splitting
- [ ] write scaling kernels using the new API
    - [ ] triangulate all cells of a mesh 
    - [ ] parallelize grisubal
