### ISSUE TITLE
rel: 0.2.0

### ISSUE THREAD

**Issue by imrn99** [LIHPC-Computational-Geometry/honeycomb#41]
# Release 0.2.0 tracker

- [x] merge the `CMap2` API rework: #30 
- [x] cleanup the core code (dead code , make a module for attribute-related stuff): #42 
- [x] adjust the getter API of `CMap2`: #45 
- [x] complete public API doc: #47 
- [x] update user guide: #44 
- [x] add a new quickstart example for the `CMap2` struct: #43 
- [x] add license / contributing information : #39 
- [x] finalize changelog & bump crate versions: #48
