### ISSUE TITLE
tracker: upgrades for the visualization tool

### ISSUE THREAD

**Issue by imrn99** [LIHPC-Computational-Geometry/honeycomb#53]
This issues tracks possible enhancements for the visualization tool implemented in the `honeycomb-render` crate. ~All of these changes will probably be packed into a patch or minor version release~ Whatever happens, happens.

- Map visualization:
    - [x] #22 
    - [x] #21, #62
    - [x] Change dart rendering workflow to have more consistent arrow size: #62 
- ~Mesh visualization~ this can be done using the I/O features #75 
    - ~Add rendering code to view the map as a mesh~
    - ~Add a way to switch between mesh and map view~
- Fix
    - [x] #20 
    - [x] upgrade render dependencies to the latest release: #70 
    - [ ] scale resolution with window size 
    - [x] avoid deformation due to change in window size: #85 
    - [x] shrink face polygons relatively to their size: #86

**Comment by imrn99** [comment]
Closing this since I plan to rewrite the render tool using `bevy` both for fun & improvements
