### ISSUE TITLE
enh: implement a builder structure for `CMap2`

### ISSUE THREAD

**Issue by imrn99** [LIHPC-Computational-Geometry/honeycomb#57]
## Blocking issue

- [x] #93

Writing such code most likely require storing type information, which I have no clue how to achieve at the moment. Some 
relevant (maybe?) ideas:
- https://stackoverflow.com/questions/48027839/how-to-box-a-trait-that-has-associated-types
- ECS impls: https://arewegameyet.rs/ecosystem/ecs/

---

Implement a new structure (probably named `CMap2Builder`) based on the [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern) to allow users to add custom attributes to their map, using the public API. 

## Information

- [x] Suggestion for a new feature

## Suggested changes

In PRs #33, #34, all the tools required for a generic attribute system were implemented. At the moment, these tools are used directly in the `CMap2` constructor and methods to handle vertices coordinates. The goal is to expose an API to the user, allowing him to add custom attributes to the map, provided that he can describe them using traits provided by the crate.

The workflow could look like this:

```rust
// define your custom attribute
struct Attribute {
    // ...
}

// implement the crate's trait for your structure
impl AttributeUpdate for Attribute {
    // ...
}

impl AttributeBind for Attribute {
    // ...
}

// optionally, implement your own storage structure
struct Storage<A: AttributeUpdate + AttributeBind> {
    // ...
}

impl<A: AttributeUpdate + AttributeBind> AttributeStorage for Storage<A> {
    // ...
}

let map = CMap2Builder::default()
    .n_darts(10)
    .add_attribute_with_storage::<Attribute, Storage>("one_attribute_key")
    .add_attribute::<Attribute>("another_attribute_key")
    .build()
    .unwrap();
```

## Questions to answer

- [x] Should vertices be included by default in the map? **YES**
- [x] How to differentiate attributes internally to ensure correct accesses? [**`TypeId`**](https://github.com/LIHPC-Computational-Geometry/honeycomb/issues/57#issuecomment-2133478092)
- [x] ~How should attribute storages be laid out in memory?~ This most likely should be an improvement, not a base feature
- [x] ~Can we use a `hint()` method to hint at the usage of the generated map (e.g. a given algorithm) & setup the memory layout accordingly?~ This most likely should be an improvement, not a base feature
- [x] Can there be some interop with the `GridBuilder` struct implemented in #60 ? **YES**
- [x] Can there be some interop with the `io` module/feature introduced in #73 ? **YES**

**Comment by imrn99** [comment]
### Should vertices be included by default in the map?


**Current answer: YES**

#### Yes

1. Having built-in vertices allow the builder API to be unified across dimensions, i.e. have a single `CMapBuilder` struct and dedicated methods to build N-maps, e.g. `CMapBuilder::build2` and `CMapBuilder::build3`.
2. This crate is an implementation of combinatorial maps **for meshing applications**; Vertices will always be used, and most likely used repeatedly in a given code. 
3. Vertex can have dedicated read/write methods implemented for the map structure, instead of a generic attribute look-up; This would likely lead to much better performance considering the point above.

#### No

1. Hardcoding vertices into the structure leads to a loss of genericity, therefore a loss of potential applications / possible usages.
2. If, for any reason, an application requires the dimension of the map to be different from the dimension of the vertices, the built-in vertices will either become useless (in favor of a custom attribute) or will work in tandem with a(n additional) custom attribute. Both are sub-optimal, the former in memory usage, the latter in memory access patterns.

#### Analysis

- *N1* arguably does not matter because of *Y2*, and it is too early/presumptuous to think that far ahead in terms of user experience. 
- *N2* can be solved, if necessary, by introducing a generic for vertex representation and giving control over the actual type to the user. This has minimal impact over the dedicated API mentioned in *Y3*.

**Comment by imrn99** [comment]
### Can there be interoperability between the builder struct and `GridBuilder` / `io` features?

**Current answer: YES**

#### Integration in the builder

Both of the features mentioned in the title can be easily added to the builder, using `Option`s in the struct:

```rust
pub struct CMapBuilder {
    // other fields...
    grid_builder: Option<GridBuilder>,
    vtk_file: Option<vtkio::model::Vtk>,
}

impl CMapBuilder {
    pub fn from_vtk_file(self, file_path: impl AsRef<Path> + Debug) -> Self {
        let file = Vtk::import(file_path).unwrap_or_else(|e| panic!("E: failed to load file: {e:?}"));
        self.vtk_file = Some(file);
        self
    }

    pub fn from_grid_builder(self, grid: GridBuilder) -> Self {
        self.grid_builder = Some(grid);
        self
    }
}
```

#### Priority system

When building the map, we can check for VTK / grid data in a specific order in order to have one overwrite the others. The ordering policy would be something along those lines: 

- Vtk overwrites 
- the Grid builder, which overwrites
- anything in conflict that comes after

**Comment by imrn99** [comment]
### How to differentiate attributes internally to ensure correct accesses?

Current answer: **TBD**

In both cases, attributes should most likely be grouped according to their binding entity.

#### The easy way

As described in the initial code snippet, we can use a some variant of `Map` structs to identify each storage using a key. The key would be a chain of character for simplicity's sake. This would be a straightforward implementation, but indexing a map using `&str`s sounds bad performance-wise and the API wouldn't look good:

```rust
fn attribute<'a, T: AttributeUpdate + AttributeBind>(&self, key: &'a str) -> T {
    // access using match on attribute bind type + str for specific storage
    // the arbitrary str seems like a good way to introduce failure into the code
}
```

#### The elegant, *may not work*, way

I recently used the `TypeId` struct (see [here](https://github.com/LIHPC-Computational-Geometry/honeycomb/pull/75#discussion_r1604478306)) to determine the type of a generic `T`. This could be use, in combination with a lightweight map (or short arrays) to organize attribute storages. At a surface level (at least), it seems better than to index storages using strings. It also leaves us with a more elegant user API:

```rust
fn attribute<T: AttributeUpdate + AttributeBind>(&self) -> T {
    // access using match on attribute bind type + typeid for specific storage
}
```

**Comment by imrn99** [comment]
@cedricchevalier19 @franck-ledoux any input? I'm planning on making a first implementation of the structure, without the custom attribute features, in order to unify the constructor API (which is all over the place atm: `CMap2::new`, `CMap2::from_vtk_file`, `GridBuilder::build`, `GridBuilder::unit_grid`, ...)

**Comment by cedricchevalier19** [comment]
Let's discuss this tomorrow
