### ISSUE TITLE
Enh: unit tests tracking

### ISSUE THREAD

**Issue by imrn99** [LIHPC-Computational-Geometry/honeycomb#6]
# Description

This issue is used to track unit testing coverage across the project.

Suggestions are welcomed.

### `honeycomb-core`

- dart  
    - [ ] DartData: Marks operations
- embed
    - [ ] Face structure
    - [ ] Custom Vec/Vertex types
- twomap
    - [ ] TwoMap: OOB & similar mistakes coverage on getters / setters
    - [ ] TwoMap: Incorrect sewing operations (darts not free, inconsistent orientation...)
    - [ ] TwoMap: Correct state after (un)sewing operations
