### ISSUE TITLE
release: `0.3.0`

### ISSUE THREAD

**Issue by imrn99** [LIHPC-Computational-Geometry/honeycomb#78]
# Release `0.3.0` tracker

To-Do:
- [x] #72 
- [x] #77 
- [x] #76, #74 
- [x] update dependencies: #81 
- [x] fix `spatial_repr` test ([#74 comment](https://github.com/LIHPC-Computational-Geometry/honeycomb/pull/74#discussion_r1601848318)): #79 
- [x] complete the changelog #80 
- [x] check if doc & user guide are up to date: #82

**Comment by imrn99** [comment]
Closed with #79
